# 100 numpy exercises

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [ ]:
!pip install jovian --upgrade --quiet

In [1]:
import jovian

In [2]:
jovian.commit(project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/100-numpy-exercises" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/math-nights/100-numpy-exercises


'https://jovian.ai/math-nights/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [ ]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.version.version)
np.show_config()

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
arr = np.zeros((10,10))
print('%d bytes' % (a.size * a.itemsize))

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.info(np.add))

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.zeros(10)
arr[4] = 1
arr

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(10, 50)
arr

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.arange(11)
arr = arr[::-1]
arr

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr = np.arange(9).reshape(3, 3)
arr

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.nonzero([1, 2, 0, 0, 4, 0])
arr

Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-100-exercises')

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
arr = np.eye(3)
arr

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr = np.random.random((3, 3, 3))
arr

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.random((10, 10))
#print(arr)
arr.min(), arr.max()

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.random.random(30)
arr.mean()

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr = np.ones((6, 6))
arr[1:-1, 1:-1] = 0
print(arr)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr = np.ones((6, 6))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
arr = np.diag(1+np.arange(4), k=-1)
arr

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr = np.zeros((8,8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(99,(6,7,8)))

Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr = np.random.random((5,5))
arr = (arr - np.mean(arr))/(np.std(arr))
arr

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
color

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
arr = np.dot(np.ones((5,3)), np.ones((3,2)))
arr

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(11)
arr[(3 < arr) & (arr < 8)] *= -1
arr

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.random.uniform(-6,+6,6)
print(np.copysign(np.ceil(np.abs(arr)), arr))

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1 = np.random.randint(0,6,6)
arr2 = np.random.randint(0,6,6)
print(np.intersect1d(arr1,arr2))

Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")
arr = np.ones(1) / 0
arr

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [ ]:
yesterday, today, tomorrow

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(6)*1
B = np.ones(6)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.uniform(0,6,6)

print(arr - arr%1)
print(arr // 1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(), dtype=float, count=-1)
print(arr)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
arr

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.random.random(10)
arr.sort()
arr

Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.arange(6)
np.add.reduce(arr)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,4,6)
B = np.random.randint(0,4,6)

equal = np.array_equal(A,B)
print(equal)

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.ones(6)
arr.flags.writeable = False
arr[0] = 0

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
arr = np.random.random((10,2))
x,y = arr[:,0], arr[:,1]
R = np.sqrt(x**2 + y**2)
T = np.arctan2(y, x)
print(R)
print(T)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arr = np.random.random(10)
arr[arr.argmax()] = 0
print(arr)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))
arr = np.zeros((4,6))
print(arr)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
arr = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(arr-v)).argmin()
print(arr[index])

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
arr = np.zeros(6, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(arr)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
arr = np.random.random((10,2))
X,Y = np.atleast_2d(arr[:,0], arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
arr = (np.random.rand(10)*100).astype(np.float32)
Y = arr.view(np.int32)
Y[:] = arr
print(Y)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
arr = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(arr)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.arange(6).reshape(3,2)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 6
p = 2
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),1)
print(arr)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
arr = np.random.rand(5, 10)

# Recent versions of numpy
Y = arr - arr.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = arr - arr.mean(axis=1).reshape(-1, 1)

print(Y)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
arr = np.random.randint(0,3,(3,10))
print((~arr.any(axis=0)).any())

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
arr = np.random.uniform(0,1,10)
a = 0.5
m = arr.flat[np.abs(arr - a).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

arr = NamedArray(np.arange(6), "range_6")
print (arr.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
arr = np.ones(10)
I = np.random.randint(0,len(arr),20)
arr += np.bincount(I, minlength=len(arr))
print(arr)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
arr = np.random.randint(0,10,(3,4,3,4))
sum = arr.sum(axis=(-2,-1))
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
arr1 = np.random.uniform(0,1,(5,5))
arr2 = np.random.uniform(0,1,(5,5))

np.diag(np.dot(arr1, arr2))

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
arr = np.array([1,2,3,4,5])
nz = 3
arr0 = np.zeros(len(arr) + (len(arr)-1)*(nz))
arr0[::nz+1] = arr
print(arr0)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
arr1 = np.ones((5,5,3))
arr2 = np.ones((5,5))
print(arr1 * arr2[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.arange(36).reshape(6,6)
arr[[0,1]] = arr[[1,0]]
print(arr)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr = np.arange(20)
print(moving_average(arr, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [5]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
arr = rolling(np.arange(10), 3)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
arr = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

arr = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [6]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [13]:
arr = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(arr) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [15]:
arr = np.random.randint(0,10,50)
print(np.bincount(arr).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [16]:
arr = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
C = stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
print(C)

[[[[0 4 0]
   [3 4 0]
   [0 0 3]]

  [[4 0 2]
   [4 0 3]
   [0 3 0]]

  [[0 2 2]
   [0 3 4]
   [3 0 0]]

  [[2 2 3]
   [3 4 1]
   [0 0 4]]

  [[2 3 4]
   [4 1 0]
   [0 4 0]]

  [[3 4 4]
   [1 0 1]
   [4 0 3]]

  [[4 4 1]
   [0 1 4]
   [0 3 3]]

  [[4 1 3]
   [1 4 0]
   [3 3 3]]]


 [[[3 4 0]
   [0 0 3]
   [2 2 4]]

  [[4 0 3]
   [0 3 0]
   [2 4 4]]

  [[0 3 4]
   [3 0 0]
   [4 4 2]]

  [[3 4 1]
   [0 0 4]
   [4 2 4]]

  [[4 1 0]
   [0 4 0]
   [2 4 4]]

  [[1 0 1]
   [4 0 3]
   [4 4 3]]

  [[0 1 4]
   [0 3 3]
   [4 3 3]]

  [[1 4 0]
   [3 3 3]
   [3 3 0]]]


 [[[0 0 3]
   [2 2 4]
   [4 4 3]]

  [[0 3 0]
   [2 4 4]
   [4 3 3]]

  [[3 0 0]
   [4 4 2]
   [3 3 1]]

  [[0 0 4]
   [4 2 4]
   [3 1 0]]

  [[0 4 0]
   [2 4 4]
   [1 0 2]]

  [[4 0 3]
   [4 4 3]
   [0 2 3]]

  [[0 3 3]
   [4 3 3]
   [2 3 1]]

  [[3 3 3]
   [3 3 0]
   [3 1 0]]]


 [[[2 2 4]
   [4 4 3]
   [3 2 2]]

  [[2 4 4]
   [4 3 3]
   [2 2 0]]

  [[4 4 2]
   [3 3 1]
   [2 0 3]]

  [[4 2 4]
   [3 1 0]
   [0 3 0]]

  [[2 4 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [17]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 16 11 13  9]
 [16  5  0  1  3]
 [11  0  6 42  8]
 [13  1 42  1 11]
 [ 9  3  8 11  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [18]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [19]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [23]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [24]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5
print(arr[np.argsort(arr)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [25]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


Save and commit your work

In [26]:
import jovian

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/100-numpy-exercises" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/math-nights/100-numpy-exercises


'https://jovian.ai/math-nights/100-numpy-exercises'

#### 91. How to create a record array from a regular array? (★★★)

In [28]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [29]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.44 s ± 25.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
488 ms ± 12.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
413 ms ± 4.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [30]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [31]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[3 3 2]
 [4 3 0]
 [2 0 4]
 [3 4 4]
 [4 3 1]
 [0 1 0]
 [4 0 4]
 [4 2 1]
 [1 0 1]
 [1 1 1]]
[[3 3 2]
 [4 3 0]
 [2 0 4]
 [3 4 4]
 [4 3 1]
 [0 1 0]
 [4 0 4]
 [4 2 1]
 [1 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [32]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [33]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [34]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.03638703, 0.05894348, 0.04354138, 0.07288457, 0.06454326,
        0.06923054, 0.02958112, 0.04485677, 0.02426708, 0.07604119],
       [0.1638017 , 0.26534297, 0.19600808, 0.32810092, 0.29055125,
        0.31165174, 0.13316387, 0.20192951, 0.10924191, 0.3423109 ],
       [0.02623803, 0.04250308, 0.0313969 , 0.05255575, 0.04654098,
        0.04992089, 0.02133041, 0.0323454 , 0.01749855, 0.05483193],
       [0.10990378, 0.17803352, 0.13151284, 0.22014136, 0.19494718,
        0.20910468, 0.08934713, 0.13548587, 0.07329654, 0.22967564],
       [0.0338918 , 0.05490145, 0.04055554, 0.06788654, 0.06011723,
        0.06448308, 0.0275526 , 0.04178073, 0.02260297, 0.07082669],
       [0.06495857, 0.10522662, 0.0777306 , 0.13011444, 0.11522343,
        0.12359121, 0.05280857, 0.08007885, 0.04332188, 0.13574966],
       [0.41922649, 0.6791065 , 0.501654  , 0.8397263 , 0.74362342,
        0.79762702, 0.34081344, 0.51680904, 0.27958868, 0.87609466],
       [0.08199644, 0.13282633, 0.0981184

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [35]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [36]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [37]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.00898575  0.35711112]


Save and commit your work

In [38]:
import jovian

In [39]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/100-numpy-exercises" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/math-nights/100-numpy-exercises


'https://jovian.ai/math-nights/100-numpy-exercises'

Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100